// <auto-generated />
namespace Demo_Login2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class _25072021V1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_25072021V1));
        
        string IMigrationMetadata.Id
        {
            get { return "202107241748286_25072021V1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
